services:
  - type: web
    name: Exam-Saarthi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py setup_admin --password admin123
    startCommand: gunicorn loginproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
