services:
  - type: web
    name: Exam-Saarthi
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input 2>&1 || true
    startCommand: python startup.py
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
