# Generated by Django 6.0.4 on 2026-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_igubcompaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGUMcomPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=50, verbose_name='Paper ID')),
                ('paper_name', models.CharField(max_length=200, verbose_name='Paper Name')),
                ('course', models.CharField(default='M.Com', max_length=100)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('3rd', '3rd Semester'), ('4th', '4th Semester')], max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('pdf_link', models.URLField(verbose_name='PDF Link / Drive Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
