from django.core.management.base import BaseCommand
from accounts.models import IGUBaPaper

class Command(BaseCommand):
    help = 'Import IGU BA papers from HTML to database'

    def handle(self, *args, **options):
        papers_data = [
            # 1st Sem
            {'paper_id': '11001', 'paper_name': 'English', 'semester': '1st', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/1ewnoRKdVcWYyegxzYyDs22hlZRxEH2YN/view'},
            {'paper_id': '11011', 'paper_name': 'Hindi', 'semester': '1st', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/1GiIRhyjcUBxF8bBWPx5A2cYhmZucaQuy/view'},
            {'paper_id': '11121', 'paper_name': 'Mathematics Algebra', 'semester': '1st', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/1GsorZIhnDLlsFD2a7t96mQlEXsX0HfpP/view'},
            {'paper_id': '11122', 'paper_name': 'Mathematics Calculus', 'semester': '1st', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/1hmUD3B_WYZtHCKDfxu1mSrMgisaiXw3f/view'},
            {'paper_id': '11123', 'paper_name': 'Mathematics Solid Geometry', 'semester': '1st', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/1Xuwcfri7YInKqJsOaxj4TVDl76MVIfUr/view'},
            {'paper_id': '11001', 'paper_name': 'English', 'semester': '1st', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1CH5QofP-2ZAvr04-FXM0Q0HZL3h-Z2yF/view'},
            {'paper_id': '11011', 'paper_name': 'Hindi', 'semester': '1st', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/13rJwLry0fns15VQfYX-IO1wKAYBUFfBa/view'},
            {'paper_id': '11041', 'paper_name': 'History of India from earliest times to c 1200', 'semester': '1st', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1oZLRptro3AjHMlZ33ceGyCQnk4P23fY8/view'},
            {'paper_id': '10361', 'paper_name': 'PS Indian Constitution', 'semester': '1st', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1-BL4mtAV5ytucWmFZcNTVIcrGFxIweue/view'},
            {'paper_id': '11081', 'paper_name': 'Sociology Basic Concept of Sociology', 'semester': '1st', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1rQvlzP6sMe6i7YgccmOBP5KKQKNCLOG8/view'},
            {'paper_id': '11001', 'paper_name': 'English', 'semester': '1st', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1j93mChMAzikm2IdW--4Vye60t8cCZRK4/view'},
            {'paper_id': '11381', 'paper_name': 'English', 'semester': '1st', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1hI3TdtfXKWZemAjkdrx8U1aiFg9HU0Ud/view'},
            {'paper_id': '11062', 'paper_name': 'Geography of India', 'semester': '1st', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1H0-lcUdSiUetvDDS2sWYwlmjXaTL4W_T/view'},
            {'paper_id': '11011', 'paper_name': 'Hindi', 'semester': '1st', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1EjbLv7RxdEtkRXKf5ex5cil-phLDY4Pn/view'},
            {'paper_id': '11181', 'paper_name': 'Mathematics-I Algebra', 'semester': '1st', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1KmLA3XJswgSkV_ZS7DzZxctljKZ441Yr/view'},
            {'paper_id': '11071', 'paper_name': 'Micro Economics', 'semester': '1st', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1-djEoMWkObZ-9D-C5JHt5P9AiMPDJOa0/view'},
            {'paper_id': '10361', 'paper_name': 'Political Science Indian Constitution', 'semester': '1st', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/11gmin_t3x2r7ImZn0u6h6waewHFtFPBd/view'},
            {'paper_id': 'N/A', 'paper_name': 'Environmental Studies', 'semester': '1st', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1s3njYbC0hid2TaaQXSbtLykbkd0ICr-2/view'},
            {'paper_id': '17671', 'paper_name': 'English Language and Communication Level-I', 'semester': '1st', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1zdwK8orGo9Tm_LwNrdtZGGdUvYlJ1BIr/view'},
            {'paper_id': '17672', 'paper_name': 'Hindi Bhasha Aur Vyakaran', 'semester': '1st', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1a5YRRsU0QcsPCEyoWOJ9LMbBuVKpn81b/view'},
            {'paper_id': '17652', 'paper_name': 'Environmental Studies', 'semester': '1st', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1rref_fHVCnB5527uwb0Ivh7BZYkBHss6/view'},
            {'paper_id': '17661', 'paper_name': 'Skill Enhancement Courses', 'semester': '1st', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1cUHpfN-9FOImJ5ZbWTs1FxzbUIOZg3t-/view'},
            # 2nd Sem
            {'paper_id': '21001', 'paper_name': 'English', 'semester': '2nd', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/14lnEHkT5bVNYUr2aPsaveMS3q4zgfEN1/view'},
            {'paper_id': '21062', 'paper_name': 'Geography Physical Geography-I', 'semester': '2nd', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/1DwGbgajdunfA_1HvGvYt1yRHBu7pS_c_/view'},
            {'paper_id': '21011', 'paper_name': 'Hindi', 'semester': '2nd', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/19lOmGyNagsUO4-BUPFu_y_lyF5DXUPeI/view'},
            {'paper_id': '21121', 'paper_name': 'Mathematics Number Theory and Trigonometry', 'semester': '2nd', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/1sK247LtrLWPImjtoeTVOOKbKtdjFOqxS/view'},
            {'paper_id': '21122', 'paper_name': 'Mathematics Ordinary Differential Equations', 'semester': '2nd', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/1wUFUz_A4anu81ahDy9Oz57qnmmWW2YIv/view'},
            {'paper_id': '21123', 'paper_name': 'Mathematics Vector Calculus', 'semester': '2nd', 'year': '2021', 'pdf_link': 'https://drive.google.com/file/d/1gOkwnWLGgbDDhKPmfq3ZUhAWiSD2SZkD/view'},
            {'paper_id': '22999', 'paper_name': 'Computer Awareness-I', 'semester': '2nd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/150rq-zK0VOO41oddhdCO48dXlFA5zvBZ/view'},
            {'paper_id': '21062', 'paper_name': 'Physical Geography', 'semester': '2nd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1hjPRgCvOztL55cJQ1baELJXmbAjUqgj7/view'},
            {'paper_id': '31361', 'paper_name': 'Defense Studies World Military History Modern', 'semester': '2nd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1NhQzw30i7mxVbVFE--D3oFcBgZixxpcO/view'},
            {'paper_id': '31001', 'paper_name': 'English', 'semester': '2nd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1LBm-vT0jQJ-us2FV2YV1EC_EvEFHdL3F/view'},
            {'paper_id': '31011', 'paper_name': 'Hindi', 'semester': '2nd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1xrFhZAZm2xzzODfu-4yLWIoAIDtFmKAG/view'},
            {'paper_id': '31041', 'paper_name': 'History of India C 1707 to 1947', 'semester': '2nd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1Ww9ZC7JaACmYouHAqkhiK4-9qtjkA719/view'},
            {'paper_id': '22703', 'paper_name': 'Communication Skills and Personality Development', 'semester': '2nd', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/12z59ys6xTAMS97TQez3nQHUhER0fKx39/view'},
            {'paper_id': '22999', 'paper_name': 'Computer Awareness', 'semester': '2nd', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1RTfz_M7cUdgZnzTnt9_GbOJXp2gsGqFm/view'},
            {'paper_id': '21001', 'paper_name': 'English', 'semester': '2nd', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1Eq_OpcXjnZYqc_kU91013HIpYMpgqj-P/view'},
            {'paper_id': '21071', 'paper_name': 'Micro Economics-II', 'semester': '2nd', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1WcJ4mHnIX-NV_QjngJZgkGiElu_5Wv7G/view'},
            {'paper_id': '21001', 'paper_name': 'English', 'semester': '2nd', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1h3BiYNZB8nz357HRhyjF16Zu-NOHR2aH/view'},
            {'paper_id': '21011', 'paper_name': 'Hindi', 'semester': '2nd', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1FoM4w1hr4vQ2LPzf48xoUkoN9va4ek30/view'},
            {'paper_id': '21041', 'paper_name': 'History of India c 1200 to 1707', 'semester': '2nd', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1phxRlxitPEJa4r7GdgvJAjrGPCODSiwL/view'},
            {'paper_id': '21051', 'paper_name': 'Political Science', 'semester': '2nd', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1pK691IvWObbr5HYKIj8gQjY14TVD9GQf/view'},
            {'paper_id': '31101', 'paper_name': 'Home Science Clothing and Textile', 'semester': '2nd', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1N4fNnzhWtn2eCpHQhFpF3y8S-1Sd_-rp/view'},
            {'paper_id': '27652', 'paper_name': 'Environmental Studies', 'semester': '2nd', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1FjgHT8UfgR7EIpDKp7vmn2zLYrN_enke/view'},
            {'paper_id': '27084', 'paper_name': 'Indian Society and Culture', 'semester': '2nd', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1WT60VKjBXAp6BQAiv1Ii2o6JfHT8QXfJ/view'},
            {'paper_id': '27271', 'paper_name': 'Pteridophytes Gymnosperms and Fossils', 'semester': '2nd', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1QdZg-Ufv90wQa2bj6BxhK94stoRQTOUp/view'},
            {'paper_id': '22999', 'paper_name': 'Basic Computer Education', 'semester': '2nd', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1_OL2lm8uCFkHNrYV2OOYfdL8GK0lNmkH/view'},
            # 3rd Sem
            {'paper_id': '31361', 'paper_name': 'Defense Studies World Military History Modern', 'semester': '3rd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1oOf15S0McGiEqjdTYLckpp45C_lwMFKQ/view'},
            {'paper_id': '31001', 'paper_name': 'English', 'semester': '3rd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/11GUW4doZjak2Q5N57sx96ztl4DCyewe3/view'},
            {'paper_id': '31001', 'paper_name': 'English December', 'semester': '3rd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1lGLpRvfM4LkDNU6l1waegaofJkAKatLN/view'},
            {'paper_id': '31011', 'paper_name': 'Hindi', 'semester': '3rd', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1VUGSlyAV2f99P9FHthOeUrerI9E5s20A/view'},
            {'paper_id': '31041', 'paper_name': 'History of India c 1707 to 1947', 'semester': '3rd', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1plJdNSDnkp5XQo-0VZ870pZA_dgQEem1/view'},
            {'paper_id': '31101', 'paper_name': 'Home Science Clothing and Textile', 'semester': '3rd', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1Qoiexot9aC1Z2KI48U2Saewbv8hh1SfQ/view'},
            {'paper_id': '41001', 'paper_name': 'English', 'semester': '4th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1kWiWHiow3Xmn_76uJPy70c8fDH-hFoFB/view'},
            {'paper_id': '41011', 'paper_name': 'Hons-Hindi', 'semester': '4th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1MjoQpdz9xY3orXz0f12BCQwP1bXRBa3T/view'},
            {'paper_id': '41062', 'paper_name': 'Human Geography', 'semester': '4th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1MTfvkP_lsgOkfSOn2V32c4k8wtdUR90w/view'},
            {'paper_id': '41123', 'paper_name': 'Mathematics Programming in C and Numerical Methods', 'semester': '4th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1DfsVTAUNT5rOOBvEQB3GVoHsPpq5_Ahq/view'},
            {'paper_id': '41122', 'paper_name': 'Mathematics Special Function and Integral', 'semester': '4th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1Ge3i-HvvophWGc4rZuL7LaLMXC7etrdQ/view'},
            {'paper_id': '41071', 'paper_name': 'Economics Macro Economics', 'semester': '4th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1SrRUC69IOOdvoi9jGIncyZjM4gvimzDN/view'},
            {'paper_id': '41001', 'paper_name': 'English', 'semester': '4th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1nznIHxJAjP4OsM31K3wxA04V-bSar9Is/view'},
            {'paper_id': '41062', 'paper_name': 'Geography Human Geography', 'semester': '4th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1KkyycVorh-fu1vxkJOHBdvWjnpDO3sZb/view'},
            {'paper_id': '41011', 'paper_name': 'Hindi', 'semester': '4th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/12ijMCfpyZKshrAALtYYuMntXxK9b53xM/view'},
            {'paper_id': '41041', 'paper_name': 'History of Haryana Earliest Times to 1947', 'semester': '4th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1VAx9An84DRuuNY1NVE3qi6BtMQmSNuIH/view'},
            {'paper_id': '41121', 'paper_name': 'Maths-I Sequences and Series', 'semester': '4th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1wNe93C3tiFIvYkxOOAUPAWsDQInkPhVr/view'},
            {'paper_id': '41122', 'paper_name': 'Maths-II Special Functions and Integral Transforms', 'semester': '4th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1La4GPmfpIwaw_YQDdEt0qY4NwtXxv0iV/view'},
            {'paper_id': '41123', 'paper_name': 'Maths-III Programming in C and Numerical Methods', 'semester': '4th', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1LQuST14Cem0Pb3ROxY6zWmvfAztjFtAh/view'},
            # 5th Sem
            {'paper_id': '5240', 'paper_name': 'Mathematics Group and Rings', 'semester': '5th', 'year': '2020', 'pdf_link': 'https://drive.google.com/file/d/1ODO7zgBYucvM2RI4soUttwdzmcVc8rv7/view'},
            {'paper_id': '5241', 'paper_name': 'Mathematics Numerical Analysis', 'semester': '5th', 'year': '2020', 'pdf_link': 'https://drive.google.com/file/d/1mVVydVQssyNpEVIsNmiUbsFJC3i-pilO/view'},
            {'paper_id': '5241', 'paper_name': 'Mathematics Numerical Analysis V2', 'semester': '5th', 'year': '2020', 'pdf_link': 'https://drive.google.com/file/d/1MIVDbvDdB4Pq1zJz9NDKOoOQknMsNW43/view'},
            {'paper_id': '51062', 'paper_name': 'Economic geography', 'semester': '5th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1broyzG0vVZoxaCa3bAHZZw3xc_zHw3f7/view'},
            {'paper_id': '51001', 'paper_name': 'English', 'semester': '5th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1MJkVKdDwEIxGiS89gk1nWdLS3kXd_H3S/view'},
            {'paper_id': '51122', 'paper_name': 'Groups and Rings', 'semester': '5th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1YTFD2C4kEJow_V95tURrJAPobOEWVAst/view'},
            {'paper_id': '51011', 'paper_name': 'Hindi', 'semester': '5th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1FjT2n2GclJCmfMEKHuPS8tyzRSwaJ_l_/view'},
            {'paper_id': '51123', 'paper_name': 'Numerical Analysis', 'semester': '5th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1DMXeWhCntzgP5af-ADFkkXeD-SD6hGTc/view'},
            {'paper_id': '51121', 'paper_name': 'Real Analysis', 'semester': '5th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1bE_4c0wNKuyWhUjW2_JLZiFb3lI-TWyz/view'},
            {'paper_id': '51391', 'paper_name': 'Sanskrit', 'semester': '5th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1Mdft5gEZEkADxFu8bOf-mA6FYMX4hCEH/view'},
            {'paper_id': '51011', 'paper_name': 'Honors', 'semester': '5th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1oSZr4fpYsKv2y5MledT_rP_N63eCwvVW/view'},
            {'paper_id': '51071', 'paper_name': 'Economics Development', 'semester': '5th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1qK3iwIFjltSlonpQkCJEUYYZpbRevWwV/view'},
            {'paper_id': '51001', 'paper_name': 'English Compulsory', 'semester': '5th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1LrUsXIeC8vxtwB_0RZ8zLUQ2K-j3YWvU/view'},
            {'paper_id': '51062', 'paper_name': 'Geography Economic Geography', 'semester': '5th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1SrRJkrrN2SwWDzj4lkGAauNchb4fA2Xe/view'},
            {'paper_id': '51011', 'paper_name': 'Hindi', 'semester': '5th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1CJspOwUy0zCjSV-m4-4IdiCYziRVQ6xf/view'},
            {'paper_id': '51041', 'paper_name': 'History Ancient and Medieval World', 'semester': '5th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/10fUG0uwybP8mZzGa-3c6WFTeKuDPj1KQ/view'},
            {'paper_id': '51121', 'paper_name': 'Mathematics-I Real Analysis', 'semester': '5th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1t9RR-1OwNDrwk1oZZnwwsLvpMSYRZrjH/view'},
            {'paper_id': '51123', 'paper_name': 'Mathematics-III Numerical Analysis', 'semester': '5th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1yvxhfI_qU-Yd5LAzxjHtVeOXf4HYubDI/view'},
            {'paper_id': '51122', 'paper_name': 'Groups and Rings', 'semester': '5th', 'year': '2023', 'pdf_link': 'https://drive.google.com/file/d/1J4jW9NXp9uvUKdGlEV5-L3i4dWQI0xtL/view'},
            {'paper_id': '51071', 'paper_name': 'Development Economics', 'semester': '5th', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1PryWUTFjn9J845C-7pGAAkjY_aHdATOy/view'},
            {'paper_id': '51001', 'paper_name': 'English', 'semester': '5th', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1LB6y4sxZN2ht3it0zPr66SEkjRmP3Gbk/view'},
            {'paper_id': '51011', 'paper_name': 'Hindi', 'semester': '5th', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1Fe--A65v6mTs9nH-TUxYfIAnWy9nx2TH/view'},
            {'paper_id': '51041', 'paper_name': 'History Ancient and Modern World', 'semester': '5th', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1By1-s4vdQ7kH0u5MCUFw7DeGd1bPZnOB/view'},
            {'paper_id': '51101', 'paper_name': 'Home Science Food and Nutrition', 'semester': '5th', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/16tevBomHIckH7qJdP65UDKez17tG0aab/view'},
            {'paper_id': '51051', 'paper_name': 'Political Science Comparative Politics', 'semester': '5th', 'year': '2024', 'pdf_link': 'https://drive.google.com/file/d/1h3rNiNSHoQjePyHaG1m89N_Fn5ov1TVq/view'},
            # 6th Sem
            {'paper_id': '61061', 'paper_name': 'Geography Remote Sensing GIS and Quantitative Method', 'semester': '6th', 'year': '2022', 'pdf_link': 'https://drive.google.com/file/d/1zK31ctXwefZi1erVNgNJX4fE_JTsl23z/view'},
            {'paper_id': '61051', 'paper_name': 'Comparative Constitution of UK and USA Political Science', 'semester': '6th', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1fy1bUy8T4UF12_PwZtSbTPUQlnIH3ooc/view'},
            {'paper_id': '61071', 'paper_name': 'International Economics', 'semester': '6th', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1XDG77Vru6WfdWBUuhb4qMeWq6Le1-PKS/view'},
            {'paper_id': '61001', 'paper_name': 'English', 'semester': '6th', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1XwfhCFjJXWcOCiiZev0gxAk0MFBJzMhf/view'},
            {'paper_id': '61062', 'paper_name': 'Geography Introduction to Remote Sensing GIS and Quantitative', 'semester': '6th', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1O-pc3akwnKiGXvwRgq3btT-w-3cDGoWh/view'},
            {'paper_id': '61011', 'paper_name': 'Hindi', 'semester': '6th', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1ZzhSJS2zR9cobftMq51CaZSAwkWSGJW4/view'},
            {'paper_id': '61121', 'paper_name': 'Maths-I Real and Complex Analysis', 'semester': '6th', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1MYMpB_i0ymgTOgUWa0CWvXz0exvYzegk/view'},
            {'paper_id': '61122', 'paper_name': 'Maths-II Linear Algebra', 'semester': '6th', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/1L6DBm4fYLq7Kh_oGTJIUeDg_nlDPyAkY/view'},
            {'paper_id': '61123', 'paper_name': 'Maths-III Dynamics', 'semester': '6th', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/18XIhBglJlqekv5p4y9W0D0GFqAKIl3BK/view'},
            {'paper_id': '61083', 'paper_name': 'Sociology-III Rural Society Structure and Change', 'semester': '6th', 'year': '2025', 'pdf_link': 'https://drive.google.com/file/d/178DUMQJorPjMA1CoF0PWQY602AcSn2_C/view'},
        ]

        for paper in papers_data:
            IGUBaPaper.objects.get_or_create(
                paper_id=paper['paper_id'],
                paper_name=paper['paper_name'],
                semester=paper['semester'],
                year=paper['year'],
                pdf_link=paper['pdf_link'],
                defaults={
                    'course': 'BA',
                }
            )
            self.stdout.write(f"Added: {paper['paper_name']} ({paper['semester']} Sem, {paper['year']})")

        self.stdout.write(self.style.SUCCESS('Successfully imported all BA papers!'))